theme: jekyll-theme-giellalt
title: Dictionary for Kildin Saami ⇒ Ter Saami
description: An electronic dictionary from Kildin Saami to Ter Saami

defaults:
  - scope: { path: "" }
    values:
      layout: default

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
